import './style/reset.style.scss'
import './style/theme.style.scss'

import type { Metadata } from 'next'
import ThemeProvider from './context/ThemeContext'
import Header from './components/header/Header'

import { Inter } from 'next/font/google'
import Footer from './components/footer/Footer'

export const metadata: Metadata = {
  title: 'Next.js, Sass, TypeScript, Radix Ui',
  description: 'Generated by create next app',
}

type AppProps = {
  children: React.ReactNode
}

const inter = Inter({
  weight: ['200', '400', '700', '900'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }: AppProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
