import './style/reset.style.scss'
import './style/global.style.scss'
import './style/theme.style.scss'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type AppProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: AppProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
